services:
  - crosbymichael/redis

build: &testImage
  - FROM ubuntu
  - RUN apt-get install -y telnet nodejs
  - RUN npm install
  - CMD ["make","test"]

images:
- feeder/buildImage:%{git.tag}-%{git.branch}-%{git.sha}: *testImage
- feeder/nginx: api/Dockerfile
